### ISSUE TITLE
Quits working and replaces💩with :poop:

### ISSUE THREAD

**Issue by methodbox** [mattbierner/vscode-emojisense#23] opened 2020-01-10 02:42 UTC
Just as it says; it replaces the actual emoji, in this case in HTML strings, with the markdown equivalent shortcut.

**Comment by mattbierner** [comment] 2020-01-15 04:04
Please provide steps to reproduce the issue

**Comment by methodbox** [comment] 2020-01-15 14:47
> Please provide steps to reproduce the issue

I just tried using the emoji (literally any emoji not just poop - was trying to be a bit silly 😜) a few times and after switching between files and adding/removing it a few times all the images stopped appearing an were instead replaced by `:emoji name:`.

Note that disabling this extension and installing an alternative that provided similar functionality worked fine; VS Code was still capable of displaying emoji.

The list of emojis no longer showed the image, either, when selecting from the list. My best guess is for some reason your extension was unable to access the cached list of images.

I assume something is provided in the extension to cause VS Code to render the images vs. showing Unicode as using plain Unicode inside VS Code does not, by default, display the actual emoji, but works or course at runtime.

**Comment by mattbierner** [comment] 2020-04-11 20:57
I'm closing this as not reproducible. 

From your description, the file rewriting sounds like it is caused by one of your other extensions. This one does not touch existing text, it only provides IntelliSense

We also don't ship images of the emoji, we use the standard emoji in text. If these are not being rendered for you, please file an issue against VS Code itself

**Closed by mattbierner** 2020-04-11 20:57 UTC
